version: '3.8'

services:
  ai_assistant_service:
    build:
      context: backend/ai_assistant_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/ai_assistant_service:/app
    env_file:
      - backend/ai_assistant_service/.env
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3

  celery_worker_ingestor:
    build:
      context: backend/ingestor_service
      dockerfile: Dockerfile
    command: celery -A app.celery.worker worker --loglevel=info -Q ingest
    volumes:
      - ./backend/ingestor_service/app:/app/app
    env_file:
      - backend/ingestor_service/.env
    depends_on:
      - redis

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  ingestor_service:
    build:
      context: backend/ingestor_service
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    volumes:
      - ./backend/ingestor_service/app:/app/app
    env_file:
      - backend/ingestor_service/.env
    depends_on:
      - redis
      - celery_worker_ingestor

  embedding_service:
    build:
      context: backend/embedding_service
      dockerfile: Dockerfile
    env_file:
      - backend/embedding_service/.env
    volumes:
      - ./backend/embedding_service/app:/app/app
    ports:
      - "8002:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - ai_assistant_service
      - ingestor_service

  qdrant_service:
    build:
      context: backend/qdrant_service
      dockerfile: Dockerfile
    env_file:
      - backend/qdrant_service/.env
    volumes:
      - ./backend/qdrant_service/app:/app/app
    ports:
      - "8003:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - qdrant
      - ai_assistant_service
      - embedding_service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:5173"

volumes:
  qdrant_data: